import Head from 'next/head'
import Image from 'next/image'
export default function Home() {
    return (
        <div>


            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >

                <div className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
                    <div className="flex-shrink-0 col">
                        {/*<img className="h-12 w-12" src="/img/logo.svg" alt="ChitChat Logo"/>*/}
                    </div>
                    <div>
                        <div className="text-xl font-medium text-black">ChitChat</div>
                        <p className="text-red-500">You have a new message!</p>
                    </div>
                </div>

            </main>

            <footer >

            </footer>
        </div>
    )
}

