import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../components/NavBar";
import { DisplayCharts } from "../components/DisplayCharts";
import { ChartResponse } from "./api/charts";

interface HomeProps {
  charts: ChartResponse[];
}
export default function Home(props: HomeProps) {
  return (
    <div>
      <Head>
        <title>METVUW MOBILE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
      </main>
      <DisplayCharts charts={props.charts} />
      <footer></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const response = await fetch("http://localhost:3000/api/charts");
  const charts = await response.json();
  return {
    props: {
      charts: charts,
    }, // will be passed to the page component as props
  };
}
