create table "public"."satellite_images" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "publicUrl" text not null,
    "url" text not null,
    "fileName" text not null,
    "width" integer not null,
    "height" integer not null,
    "year" integer not null,
    "month" integer not null,
    "day" integer not null,
    "hour" integer not null,
    "imageDateISO" timestamp with time zone not null,
    "imageDateUTC" timestamp with time zone not null
);


alter table "public"."satellite_images" enable row level security;

CREATE UNIQUE INDEX satellite_images_pkey ON public.satellite_images USING btree (id);

alter table "public"."satellite_images" add constraint "satellite_images_pkey" PRIMARY KEY using index "satellite_images_pkey";

grant delete on table "public"."satellite_images" to "anon";

grant insert on table "public"."satellite_images" to "anon";

grant references on table "public"."satellite_images" to "anon";

grant select on table "public"."satellite_images" to "anon";

grant trigger on table "public"."satellite_images" to "anon";

grant truncate on table "public"."satellite_images" to "anon";

grant update on table "public"."satellite_images" to "anon";

grant delete on table "public"."satellite_images" to "authenticated";

grant insert on table "public"."satellite_images" to "authenticated";

grant references on table "public"."satellite_images" to "authenticated";

grant select on table "public"."satellite_images" to "authenticated";

grant trigger on table "public"."satellite_images" to "authenticated";

grant truncate on table "public"."satellite_images" to "authenticated";

grant update on table "public"."satellite_images" to "authenticated";

grant delete on table "public"."satellite_images" to "service_role";

grant insert on table "public"."satellite_images" to "service_role";

grant references on table "public"."satellite_images" to "service_role";

grant select on table "public"."satellite_images" to "service_role";

grant trigger on table "public"."satellite_images" to "service_role";

grant truncate on table "public"."satellite_images" to "service_role";

grant update on table "public"."satellite_images" to "service_role";


